# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-11-22 21:27+0000\n"
"PO-Revision-Date: 2022-11-24 20:15+0000\n"
"Last-Translator: Kentaro Hayashi <kenhys@gmail.com>\n"
"Language-Team: Japanese <https://hosted.weblate.org/projects/debexpo/tools/"
"ja/>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 4.15-dev\n"

#: tools/debian/changes.py
#, python-brace-format
msgid "Changes file {filename} could not be parsed"
msgstr "Changesファイル {filename} をパースできません"

#: tools/debian/changes.py
#, python-brace-format
msgid "Changes file invalid. Missing key {key}"
msgstr "Changesファイルが正しくありません。{key}が抜けています"

#: tools/debian/changes.py
msgid ""
"dsc is missing from changes\n"
"Make sure you include the full source (if you are using sbuild make sure to "
"use the --source option or the equivalent configuration item; if you are "
"using dpkg-buildpackage directly use the default flags or -S for a source "
"only upload)"
msgstr ""
"dscがchangesファイルに含まれていません\n"
"ソースがすべてそろっていることを確認してください。(sbuildを使っているなら --"
"source オプションあるいは同等な設定を使ってください。dpkg-buildpackageを使っ"
"ているなら既定もしくは-Sでソースのみのアップロードをしてください)"

#: tools/debian/changes.py
#, python-brace-format
msgid ""
"{source} exists in the official Debian archive with the version {version}/"
"{distribution}. You may not upload a lower or equal version to this one."
msgstr ""
"{source}はDebian公式のアーカイブにバージョン{version}/{distribution}として存"
"在します。これと同じかそれより古いバージョンはアップロードできません。"

#: tools/debian/control.py
#, python-brace-format
msgid "Failed to parse debian/control:{message}"
msgstr "debian/controlのパースに失敗しました：{message}"

#: tools/debian/control.py
msgid "No source definition found"
msgstr "ソースの定義がありません"

#: tools/debian/control.py
msgid "No binary definition found"
msgstr "バイナリーの定義がありません"

#: tools/debian/control.py
#, python-brace-format
msgid "Missing key {key} in source definition"
msgstr "{key}がソースの定義にありません"

#: tools/debian/copyright.py
#, python-brace-format
msgid "Failed to parse debian/copyright: {message}"
msgstr "debian/copyrightのパースに失敗しました: {message}"

#: tools/debian/dsc.py
#, python-brace-format
msgid "{dsc} could not be parsed"
msgstr "{dsc} をパースできませんでした"

#: tools/debian/dsc.py
#, python-brace-format
msgid "Missing key {key}"
msgstr "{key}がありません"

#: tools/debian/origin.py
#, python-brace-format
msgid "Failed to retrive origin info: {e}"
msgstr "オリジンの情報を取得に失敗しました: {e}"

#: tools/debian/origin.py
#, python-brace-format
msgid ""
"Source package origin file differs from the official archive:\n"
"\n"
"Origin file         : {origin}\n"
"\n"
"sha256sum in upload : {upload}\n"
"sha256sum in archive: {archive}"
msgstr ""
"ソースパッケージのオリジンが公式アーカイブのものと異なっています：\n"
"\n"
"オリジンファイル         : {origin}\n"
"\n"
"アップロードしたsha256sum : {upload}\n"
"公式アーカイブのsha256sum: {archive}"

#: tools/debian/source.py
#, python-brace-format
msgid "Internal error. Please contact debexpo administrators at {email}"
msgstr "内部エラーが発生しました。debexpo 管理者である {email} に連絡してください"

#: tools/debian/source.py
#, python-brace-format
msgid "Could not extract source package from {dsc}: {e}"
msgstr "ソースパッケージを{dsc}から展開できませんでした： {e}"

#: tools/debian/source.py
#, python-brace-format
msgid "Could not extract source package from {dsc}: extraction took too long"
msgstr "{dsc}からソースパッケージを展開できませんでした：展開に時間がかかりすぎました"

#: tools/files.py
#, python-brace-format
msgid "No checksum method available for file {filename}."
msgstr "{filename}に関してチェックサムを計算できません。"

#: tools/files.py
#, python-brace-format
msgid ""
"Checksum failed for file {filename}.\n"
"\n"
"Expected: {expected}\n"
"Computed: {computed}"
msgstr ""
"{filename}のチェックサムが失敗しました。\n"
"\n"
"想定のチェックサム：{expected}\n"
"実際のチェックサム：{computed}"

#: tools/files.py
#, python-brace-format
msgid "{filename} is missing from upload"
msgstr "{filename} がアップロードに含まれていません"

#: tools/gnupg.py
#, python-brace-format
msgid ""
"Unable to verify file {filename}. No public key found for key {fingerprint}"
msgstr "ファイル {filename}を検証できません。 {fingerprint}の公開鍵がみつかりません"

#: tools/gnupg.py
#, python-brace-format
msgid "{filename}: not a GPG signed file"
msgstr "{filename}：GPGで署名されていないファイルです"

#: tools/gnupg.py
#, python-brace-format
msgid "Unknown GPG error. Output was: {output}"
msgstr "GPGエラーが発生しました。出力結果：{output}"

#: tools/gnupg.py
#, python-brace-format
msgid "Cannot add key: {key}"
msgstr "{key}を追加できません"
